import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ibmPlexSans,
  poppins,
  heebo,
  andika,
  roboto,
  figtree,
  inter,
  montserrat,
  redHatDisplay,
} from "@/app/font";
import "./globals.css";
import NextdoorTracker from "@/components/NextdoorTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Care Direct Recruitment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ibmPlexSans.variable} ${poppins.variable} ${heebo.variable} ${andika.variable} ${roboto.variable} ${figtree.variable} ${inter.variable} ${montserrat.variable} ${redHatDisplay.variable}`}
    >
      <head>
      <Script id="nextdoor-pixel"  strategy="afterInteractive">
    {`!function(e,n){var t,p;e.ndp||((t=e.ndp=function(){
    t.handleRequest?t.handleRequest.apply(t,arguments):t.queue.push(arguments)
    }).queue=[],t.v=1,(p=n.createElement(e="script")).async=!0,
    p.src="https://ads.nextdoor.com/public/pixel/ndp.js?id=b36a23e1-b0cb-4200-9b24-0fa1f9fd3863",
    (n=n.getElementsByTagName(e)[0]).parentNode.insertBefore(p,n))
    }(window,document);

    ndp('init','b36a23e1-b0cb-4200-9b24-0fa1f9fd3863', {});
    ndp('track','PAGE_VIEW');`}
      </Script>
 
     
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <noscript>
    <img height="1" width="1" style={{display:'none'}}
       src="https://flask.nextdoor.com/pixel?pid=b36a23e1-b0cb-4200-9b24-0fa1f9fd3863&ev=PAGE_VIEW&noscript=1"/>
  </noscript>
    <NextdoorTracker />
        {children}
      </body>
    </html>
  );
}
